<section class="bg-white py-12" id="events">
    <div class="w-full px-4 sm:px-8 lg:px-16">
        <h2 class="text-3xl font-bold text-votum-blue mb-8 text-center">Čo nás čaká?</h2>

        <div class="grid md:grid-cols-2 gap-8">
            <!-- Calendar -->
            <div>
                <div class="flex items-center justify-between mb-4">
                    <button id="prevMonth" class="bg-votum-blue text-white px-5 py-3 rounded hover-scale text-2xl md:text-3xl">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <h3 id="currentMonth" class="text-2xl font-bold text-votum-blue text-center flex-1">
                        <!-- dynamic -->
                    </h3>
                    <button id="nextMonth" class="bg-votum-blue text-white px-5 py-3 rounded hover-scale text-2xl md:text-3xl">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                </div>

                <div class="bg-votum-cream rounded-lg p-4">
                    <div class="grid grid-cols-7 gap-2 mb-4">
                        <div class="text-center font-bold text-sm">Po</div>
                        <div class="text-center font-bold text-sm">Ut</div>
                        <div class="text-center font-bold text-sm">St</div>
                        <div class="text-center font-bold text-sm">Št</div>
                        <div class="text-center font-bold text-sm">Pi</div>
                        <div class="text-center font-bold text-sm">So</div>
                        <div class="text-center font-bold text-sm">Ne</div>
                    </div>
                    <div id="calendarGrid" class="grid grid-cols-7 gap-2">
                        <!-- Days will be generated by JavaScript -->
                    </div>
                </div>
                <button class="mt-4 w-full bg-votum-blue text-white py-2 rounded-lg hover-scale text-xl">
                    <i class="fas fa-calendar-plus mr-2 py-6"></i>Uložiť do môjho kalendára
                </button>
            </div>

            <!-- Events List -->
            <div>
                <h3 class="text-xl font-bold text-votum-blue mb-4">Nadchádzajúce udalosti</h3>
                <div id="eventsList" class="space-y-4">
                    <!-- Events will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>
</section>


<script>
    // Events data
    const events = [
        { date: '2025-08-09', title: 'Koncert', description: 'Letný hudobný večer' },
        { date: '2025-08-29', title: 'Tábor', description: 'Letný detský tábor' },
        { date: '2025-09-15', title: 'Konferencia', description: 'Mladí lídri 2025' },
        { date: '2025-10-05', title: 'Workshop', description: 'Osobnostný rozvoj' }
    ];

    // Calendar state
    let currentDate = new Date();
    const monthNames = [
        'Január', 'Február', 'Marec', 'Apríl', 'Máj', 'Jún',
        'Júl', 'August', 'September', 'Október', 'November', 'December'
    ];

    function generateCalendar(year, month) {
        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const daysInMonth = lastDay.getDate();
        const startingDayOfWeek = firstDay.getDay();

        // Adjust for Monday start (0 = Monday, 6 = Sunday)
        const adjustedStart = startingDayOfWeek === 0 ? 6 : startingDayOfWeek - 1;

        const calendarGrid = document.getElementById('calendarGrid');
        calendarGrid.innerHTML = '';

        // Add empty cells for days before month starts
        for (let i = 0; i < adjustedStart; i++) {
            const emptyDay = document.createElement('div');
            emptyDay.className = 'calendar-day';
            calendarGrid.appendChild(emptyDay);
        }

        // Add days of month
        for (let day = 1; day <= daysInMonth; day++) {
            const dayCell = document.createElement('div');
            dayCell.className = 'calendar-day text-center p-1 bg-white rounded';
            dayCell.textContent = day;

            // Check if this day has an event
            const dateString = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
            const hasEvent = events.some(event => event.date === dateString);

            if (hasEvent) {
                dayCell.classList.add('event-day');
            }

            calendarGrid.appendChild(dayCell);
        }

        // Update month title
        document.getElementById('currentMonth').textContent = `${monthNames[month]} ${year}`;
    }

    // Function to generate events list
    function generateEventsList() {
        const eventsList = document.getElementById('eventsList');
        eventsList.innerHTML = '';

        // Filter events for current and future months
        const currentMonth = currentDate.getMonth();
        const currentYear = currentDate.getFullYear();

        // Display up to 5 upcoming events
        const sortedEvents = events.sort((a, b) => new Date(a.date) - new Date(b.date));

        sortedEvents.forEach(event => {
            const eventDate = new Date(event.date);
            const eventDiv = document.createElement('div');
            eventDiv.className = 'bg-votum-cream p-4 rounded-lg flex justify-between items-center';
            eventDiv.innerHTML = `
                <div>
                    <h4 class="font-bold text-votum-blue text-xl">${eventDate.getDate()}.${eventDate.getMonth() + 1}. ${event.title}</h4>
                </div>
                <button class="text-lg bg-white px-5 py-3 rounded hover-scale text-votum-blue font-semibold">
                    Viac<i class="pl-2 fas fa-arrow-right"></i>
                </button>
            `;
            eventsList.appendChild(eventDiv);
        });

    }

    // Event listeners for month navigation
    document.getElementById('prevMonth').addEventListener('click', () => {
        currentDate.setMonth(currentDate.getMonth() - 1);
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    });

    document.getElementById('nextMonth').addEventListener('click', () => {
        currentDate.setMonth(currentDate.getMonth() + 1);
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    });

    // Initialize calendar and events on page load
    generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    generateEventsList();
</script>
