<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\EventDate;

class EventSeeder extends Seeder
{
    public function run(): void
    {

        $events = [
            [
                'title_sk' => 'Tvorba Adventných vencov',
                'title_en' => 'Advent Wreath Workshop',
                'content_sk' => 'Pripojte sa k nám na tvorivú dielňu, kde si spoločne vytvoríme adventné vence.',
                'content_en' => 'Join us for a creative workshop where we will make advent wreaths together.',
                'inCalendar' => true,
                'inHome' => true,
                'inGallery' => false,
                'archived' => false,
                'color' => 'c1',
                'exact' => true,
                'dates' => ['2025-11-27', '2025-11-28', '2025-11-29'],
            ],
            [
                'title_sk' => 'Koncert Kapely VOTUM na Bratislavských Vianociach',
                'title_en' => 'VOTUM Band Concert at Bratislava Christmas',
                'content_sk' => 'Príďte si vychutnať vianočný koncert našej kapely na Františkánskom námestí.',
                'content_en' => 'Come and enjoy our Christmas concert at Franciscan Square.',
                'inCalendar' => true,
                'inHome' => true,
                'inGallery' => false,
                'archived' => false,
                'color' => 'c2',
                'exact' => true,
                'dates' => ['2025-12-07'],
            ],
            [
                'title_sk' => 'Adventný koncert a večierok v Marianke',
                'title_en' => 'Advent Concert and Party in Marianka',
                'content_sk' => 'Adventný koncert spojený s večierkom v Marianke.',
                'content_en' => 'Advent concert combined with a party in Marianka.',
                'inCalendar' => true,
                'inHome' => false,
                'inGallery' => false,
                'archived' => false,
                'color' => 'c3',
                'exact' => true,
                'dates' => ['2025-12-14'],
            ],
            [
                'title_sk' => 'Ponuka vianočných oplátok',
                'title_en' => 'Christmas Wafers Offer',
                'content_sk' => 'Vianočné oplátky spojené s podporou združenia Votum dostupné vo farnostiach Teplická a Marianka.',
                'content_en' => 'Christmas wafers supporting VOTUM association available in Teplická and Marianka parishes.',
                'inCalendar' => true,
                'inHome' => false,
                'inGallery' => false,
                'archived' => false,
                'color' => 'c4',
                'exact' => true,
                'dates' => [
                    '2025-12-01', '2025-12-02', '2025-12-03', '2025-12-04', '2025-12-05',
                    '2025-12-06', '2025-12-07', '2025-12-08', '2025-12-09', '2025-12-10',
                    '2025-12-11', '2025-12-12', '2025-12-13', '2025-12-14', '2025-12-15',
                    '2025-12-16', '2025-12-17', '2025-12-18', '2025-12-19', '2025-12-20',
                    '2025-12-21', '2025-12-22',
                ],
            ],
            [
                'title_sk' => 'Farský ples vo farnosti Teplická',
                'title_en' => 'Parish Ball at Teplická Parish',
                'content_sk' => 'Farský ples s vystúpením našich Votumákov.',
                'content_en' => 'Parish ball with performance by our VOTUM members.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => false,
                'archived' => true,
                'color' => 'c5',
                'exact' => true,
                'dates' => ['2026-02-07'],
            ],
            [
                'title_sk' => 'Letný koncert vo V-klube',
                'title_en' => 'Summer Concert at V-club',
                'content_sk' => 'Letný koncert pre rodičov, priateľov a podporovateľov.',
                'content_en' => 'Summer concert for parents, friends and supporters.',
                'inCalendar' => true,
                'inHome' => false,
                'inGallery' => false,
                'archived' => false,
                'color' => 'c6',
                'exact' => true,
                'dates' => ['2026-05-31'],
            ],
            [
                'title_sk' => 'Letný kemp v Marianke',
                'title_en' => 'Summer Camp in Marianka',
                'content_sk' => 'Týždeň plný športu, hudby, tanca, tvorivých dielní a smiechu.',
                'content_en' => 'A week full of sports, music, dance, creative workshops and laughter.',
                'inCalendar' => true,
                'inHome' => true,
                'inGallery' => false,
                'archived' => false,
                'color' => 'c7',
                'exact' => true,
                'dates' => ['2026-07-06','2026-07-07','2026-07-08','2026-07-09','2026-07-10'],
            ],








            [
                'title_sk' => 'Športovanie na ľade',
                'title_en' => 'Ice Sports',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2017-12-01'],
                'files' => ['https://photos.app.goo.gl/5y1wGPGBe1XV6HCF7'],

            ],
            [
                'title_sk' => 'Tučepi',
                'title_en' => 'Tučepi',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2017-09-09','2017-09-10','2017-09-11','2017-09-12','2017-09-13','2017-09-14','2017-09-15','2017-09-16'],
                'files' => ['https://photos.app.goo.gl/nrUApVe8FShAKHhA7'],

            ],
            [
                'title_sk' => 'Tučepi',
                'title_en' => 'Tučepi',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2018-09-01','2018-09-02','2018-09-03','2018-09-04','2018-09-05','2018-09-06','2018-09-07','2018-09-08'],
                'files' => ['https://photos.app.goo.gl/BjjwdDZuWVrYHNuD6'],

            ],
            [
                'title_sk' => 'Vianoce v Rafaeli',
                'title_en' => 'Christmas in Rafaeli',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2018-12-14'],
                'files' => ['https://photos.app.goo.gl/EDreT2xA4dQWZogd6'],

            ],
            [
                'title_sk' => 'Farský ples',
                'title_en' => 'Ball',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2019-01-19'],
                'files' => ['https://photos.app.goo.gl/nB5TRMTFGHmf9wpaA'],

            ],
            [
                'title_sk' => 'Tučepi',
                'title_en' => 'Tučepi',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2019-07-31','2019-08-01','2019-08-02','2019-08-03','2019-08-04','2019-08-05','2019-08-06','2019-08-07'],
                'files' => ['https://photos.app.goo.gl/u1NPMbYdjcxa6BNv8'],

            ],
            [
                'title_sk' => 'Letný kemp',
                'title_en' => 'Summer Camp',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2020-07-06','2020-07-07','2020-07-08','2020-07-09','2020-07-10'],
                'files' => ['https://photos.app.goo.gl/QNTYethc7bE7KaGx9'],

            ],
            [
                'title_sk' => 'Hudba v Medickej záhrade',
                'title_en' => 'Music in Medická Garden',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2020-03-01'],
                'files' => ['https://photos.app.goo.gl/rQC1uEPyHpgJjYFC6'],

            ],
            [
                'title_sk' => 'Dóm sv. Martina, podpora cez stream',
                'title_en' => 'St. Martin\'s Cathedral, streamed support',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2020-12-06'],
                'files' => ['https://photos.app.goo.gl/GJ69t7JUv8VcDUrFA'],

            ],
            [
                'title_sk' => 'Výroba darčekov pre Európske sociálne dni',
                'title_en' => 'Gift Making for European Social Days',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2021-03-01'],
                'files' => ['https://photos.app.goo.gl/HKnYwAZVLHbRQxvw5'],

            ],
            [
                'title_sk' => 'Koncert V-klub',
                'title_en' => 'V-club Concert',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2021-06-27'],
                'files' => ['https://photos.app.goo.gl/mPmXyNBj75Co2ZMWA'],

            ],
            [
                'title_sk' => 'Letný kemp',
                'title_en' => 'Summer Camp',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2021-07-12','2021-07-13','2021-07-14','2021-07-15','2021-07-16'],
                'files' => ['https://photos.app.goo.gl/WukhkxivtXBYWBNHA'],

            ],
            [
                'title_sk' => 'Tučepi',
                'title_en' => 'Tučepi',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2021-09-04','2021-09-05','2021-09-06','2021-09-07','2021-09-08','2021-09-09','2021-09-10','2021-09-11'],
                'files' => ['https://photos.app.goo.gl/DPHgxNgGoEL21Q3G8'],

            ],
            [
                'title_sk' => 'Výroba adventných vencov',
                'title_en' => 'Advent Wreath Making',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2022-11-25'],
                'files' => ['https://photos.app.goo.gl/xpfvNzZ9ZAzPM6Hi6'],

            ],
            [
                'title_sk' => 'Adventné vystúpenie: Nereálna realita?',
                'title_en' => 'Advent Performance: Unreal Reality?',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2022-06-27'],
                'files' => ['https://photos.app.goo.gl/susNhHWKENhsCUuG8'],

            ],
            [
                'title_sk' => 'Stretnutie s pracovníkmi sekretariátu KBS',
                'title_en' => 'Meeting with KBS Secretariat Staff',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2022-05-06'],
                'files' => ['https://photos.app.goo.gl/n2SrzT5tqyhfPPey8'],

            ],
            [
                'title_sk' => 'Komunitné stretnutie v Medickej záhrade',
                'title_en' => 'Community Meeting in Medická Garden',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2022-06-27'],
                'files' => ['https://photos.app.goo.gl/jEB18WJgVZsdajTx7'],

            ],
            [
                'title_sk' => 'Koncert V-klub',
                'title_en' => 'V-club Concert',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2022-06-26'],
                'files' => ['https://photos.app.goo.gl/Gv3UjQohsSw4DLg49'],

            ],
            [
                'title_sk' => 'Letný kemp',
                'title_en' => 'Summer Camp',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2022-07-11','2022-07-12','2022-07-13','2022-07-14','2022-07-15'],
                'files' => ['https://photos.app.goo.gl/nZvmVZVsqVMmzPiF8'],

            ],
            [
                'title_sk' => 'Muzikoterapia',
                'title_en' => 'Music therapy',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2022-03-01'],
                'files' => ['https://photos.app.goo.gl/hxm2pFMmAzozLiE3A'],

            ],
            [
                'title_sk' => 'Tučepi',
                'title_en' => 'Tučepi',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2022-09-03','2022-09-04','2022-09-05','2022-09-06','2022-09-07','2022-09-08','2022-09-09','2022-09-10'],
                'files' => ['https://photos.app.goo.gl/eLVwWVom7a3niq2f8'],

            ],

            [
                'title_sk' => 'Oslava konca školského roku na Teplickej',
                'title_en' => 'End of School Year Celebration at Teplická',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2023-06-23'],
                'files' => ['https://photos.app.goo.gl/WPmS6DtQ72cK4zv4A'],

            ],
            [
                'title_sk' => 'Farský ples',
                'title_en' => 'Ball',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2023-04-02'],
                'files' => ['https://photos.app.goo.gl/eJLkmZ3hDdzXcLUd8'],

            ],
            [
                'title_sk' => 'Gala koncert, 30 rokov VOTUMu',
                'title_en' => 'Gala Concert, 30 Years of VOTUM',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2023-12-10'],
                'files' => ['https://photos.app.goo.gl/quNCkJZPQyQ5nUui6'],

            ],
            [
                'title_sk' => 'Koncert V-klub',
                'title_en' => 'V-club Concert',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2023-06-04'],
                'files' => ['https://photos.app.goo.gl/Nq1w6yj6kRZ9xxzg8'],

            ],
            [
                'title_sk' => 'Letný kemp',
                'title_en' => 'Summer Camp',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2023-07-04','2023-07-05','2023-07-06','2023-07-07','2023-07-08'],
                'files' => ['https://photos.app.goo.gl/TaY4hp7CgsrVsM9u6'],

            ],
            [
                'title_sk' => 'Muzikoterapia',
                'title_en' => 'Music therapy',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2023-03-01'],
                'files' => ['https://photos.app.goo.gl/FpUfUuW2uqDCNVje7'],

            ],
            [
                'title_sk' => 'Slávnostná svätá omša 30 rokov VOTUMu',
                'title_en' => 'Festive Mass, 30 Years of VOTUM',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2023-11-15'],
                'files' => ['https://photos.app.goo.gl/6tTTmZ7KvmSZkq5e7'],

            ],
            [
                'title_sk' => 'Tučepi',
                'title_en' => 'Tučepi',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2023-09-03','2023-09-04','2023-09-05','2023-09-06','2023-09-07','2023-09-08','2023-09-09','2023-09-10'],
                'files' => ['https://photos.app.goo.gl/m5zYQBdqzD1XdaZw7'],

            ],
            [
                'title_sk' => 'Tvorba vianočných darčekov',
                'title_en' => 'Christmas Gift Making',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2023-12-01'],
                'files' => ['https://photos.app.goo.gl/1REYwJvmzzKK7pHSA'],

            ],
            [
                'title_sk' => 'Komunita v Medickej záhrade',
                'title_en' => 'Community in Medická Garden',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2023-06-27'],
                'files' => ['https://photos.app.goo.gl/6gVhRfFcExmMmtjS9'],

            ],
            [
                'title_sk' => 'Noc hudby',
                'title_en' => 'Night of Music',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2024-06-21'],
                'files' => ['https://photos.app.goo.gl/RZshJ9eDmET98RPG6'],

            ],
            [
                'title_sk' => 'Jubileum Janky Hodekovej',
                'title_en' => 'Janka Hodeková Jubilee',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2024-10-25'],
                'files' => ['https://photos.app.goo.gl/7wD58EAXMNMbozYy8'],

            ],
            [
                'title_sk' => 'Koncert Primaciálny palác',
                'title_en' => 'Concert at Primatial Palace',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2024-03-22'],
                'files' => ['https://photos.app.goo.gl/fknzMfTMPeqzL1KQ8'],

            ],
            [
                'title_sk' => 'Koncert V-klub',
                'title_en' => 'V-club Concert',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2024-06-02'],
                'files' => ['https://photos.app.goo.gl/BbkPWgMqEwfbqUbt5'],

            ],
            [
                'title_sk' => 'Letný kemp',
                'title_en' => 'Summer Camp',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2024-07-08','2024-07-09','2024-07-10','2024-07-11','2024-07-12'],
                'files' => ['https://photos.app.goo.gl/6PqTsuD6qbat5freA'],

            ],
            [
                'title_sk' => 'Muzikoterapia',
                'title_en' => 'Music therapy',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2024-03-01'],
                'files' => ['https://photos.app.goo.gl/rNLt3jcGyDUncyzf8'],

            ],
            [
                'title_sk' => 'Farský ples',
                'title_en' => 'Ball',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2024-03-02'],
                'files' => ['https://photos.app.goo.gl/qMDF18JuMSDfSkECA'],

            ],
            [
                'title_sk' => 'Koncert, Sviatky na Františkánskom',
                'title_en' => 'Concert, Holidays at Franciscan Square',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2024-12-06'],
                'files' => ['https://photos.app.goo.gl/Mx1MT5HRQXZ3TJpG8'],

            ],
            [
                'title_sk' => 'Tučepi',
                'title_en' => 'Tučepi',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2024-09-01','2024-09-02','2024-09-03','2024-09-04','2024-09-05','2024-09-06','2024-09-07','2024-09-08'],
                'files' => ['https://photos.app.goo.gl/LrFj6PE1PjV23veaA'],

            ],
            [
                'title_sk' => 'Adventný večierok',
                'title_en' => 'Advent Party',
                'content_sk' => '',
                'content_en' => '',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2024-12-15'],
                'files' => ['https://photos.app.goo.gl/6NVWRmvtHJiMjjMX9'],

            ],
            [
                'title_sk' => 'Stretká na teplickej',
                'title_en' => 'Meetups at Teplická',
                'content_sk' => 'Na Teplickej  prebiehajú stretká s témou svätých, ktorí nás svojim príkladom inšpirujú.',
                'content_en' => 'At Teplická, we have regular meetings about saints who inspire us with their lives.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2025-12-01'],
                'main_pic' => 'images/events/teplicka2025.jpg',
                'files' => ['https://photos.app.goo.gl/F7HMErrxW15t1sNR8'],

            ],
            [
                'title_sk' => 'Farský ples',
                'title_en' => 'Ball',
                'content_sk' => 'Aj tento rok sme sa spoločne zabavili pri rozhovoroch, tanci, hudbe a dobrom jedle. ',
                'content_en' => 'This year, we again enjoyed talking, dancing, music, and good food together.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2025-09-02'],
                'main_pic' => 'images/events/ples2025.jpg',
                'files' => ['https://photos.app.goo.gl/YP1roP15e5tCvsrW9'],

            ],
            [
                'title_sk' => 'Koncert, Festival zo srdca',
                'title_en' => 'Concert, Festival from the Heart',
                'content_sk' => 'Prvýkrát sme odohrali koncert na Festivale Starého mesta "Zo srdca".',
                'content_en' => 'For the first time, we played a concert at the Old Town Festival "From the Heart."',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2025-09-13'],
                'main_pic' => 'images/events/zosrdca2025.jpg',
                'files' => ['https://photos.app.goo.gl/doJf4ZoZWK4H2s486'],

            ],
            [
                'title_sk' => 'Koncert V-klub',
                'title_en' => 'V-club Concert',
                'content_sk' => 'Muzikoterapeutická technika vystupovania priniesla našim mladým možnosť sebavyjadrenia a plné publikum im darovalo svoje uznanie.  ',
                'content_en' => 'Music therapy performances gave our young people a chance to express themselves, and the full audience showed their support.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2025-06-01'],
                'main_pic' => 'images/events/vklub2025.jpg',
                'files' => ['https://photos.app.goo.gl/v9pnBG16MLaccWVW9'],

            ],
            [
                'title_sk' => 'Letný kemp',
                'title_en' => 'Summer Camp',
                'content_sk' => 'Marianka a jej príroda nám opäť ponúkla krásny čas plný zážitkov.',
                'content_en' => 'Marianka and its nature gave us another beautiful time full of experiences.',
                'inCalendar' => false,
                'inHome' => true,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2025-06-30','2025-07-01','2025-07-02','2025-07-03','2025-07-04'],                'main_pic' => 'images/events/kemp2025.jpg',
                'files' => ['https://photos.app.goo.gl/79jbdCDyapobCXkB6'],

            ],
            [
                'title_sk' => 'Muzikoterapia',
                'title_en' => 'Music therapy',
                'content_sk' => 'Muzikoterapeutické skupinové stretnutia prebiehajúce v priestoroch CikCak centra. ',
                'content_en' => 'Music therapy group sessions, taking place in the CikCak center.',
                'inCalendar' => false,
                'inHome' => true,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2025-09-01'],
                'main_pic' => 'images/events/muziko2025.jpg',
                'files' => ['https://photos.app.goo.gl/8AYfQwpou6UGTEZX9'],

            ],
            [
                'title_sk' => 'Plávanie',
                'title_en' => 'Swimming',
                'content_sk' => 'V spolupráci s Mestom Bratislava sme zahájili projekt "Život je pohyb" a naši mladí sa rozpohybovali aj vďaka profesionálnym trénerkam plávania. ',
                'content_en' => 'Together with the City of Bratislava, we started the project "Life is Movement," and our young people became more active thanks to professional swimming coaches.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'dates' => ['2025-08-01'],
                'main_pic' => 'images/events/plávanie2025.jpg',
                'files' => ['https://photos.app.goo.gl/UM8RJmzmDMTPTPt48'],

            ],
            [
                'title_sk' => 'Koncert, Sviatky na Františkánskom',
                'title_en' => 'Concert, Holidays at Franciscan Square',
                'content_sk' => 'V spolupráci s BKIS sme opäť mohli vystúpiť na Vianočných trhoch pre úžasné publikum. ',
                'content_en' => 'Together with BKIS, we performed again at the Christmas markets for a great audience.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2025-12-07'],
                'main_pic' => 'images/events/frantiskarske2025.jpg',
                'files' => ['https://photos.app.goo.gl/c5834kNTqoEgLqHp9'],

            ],
            [
                'title_sk' => 'Adventný večierok',
                'title_en' => 'Advent Party',
                'content_sk' => 'V priestoroch Obecného domu Marianka dostal každý hudobnú príležitosť v bezpečenom priestore našej komunity. ',
                'content_en' => 'In the Municipal House in Marianka, everyone had a chance to play music in a safe community space.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2025-12-14'],
                'main_pic' => 'images/events/advent2025.jpg',
                'files' => ['https://photos.app.goo.gl/hGscYh4zkaMHfBbdA'],

            ],
            [
                'title_sk' => 'Korčulovanie na ľade',
                'title_en' => 'Ice Skating',
                'content_sk' => 'Oprášili sme to, čo sme sa kedysi na ľade naučili v rámci psychomotorického programu. ',
                'content_en' => 'We practiced again what we had once learned on the ice in a psychomotor program.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'exact' => true,
                'dates' => ['2025-12-18'],
                'main_pic' => 'images/events/korčulovanie2025.jpg',
                'files' => ['https://photos.app.goo.gl/tjf2EknoaQ2qZDFLA'],

            ],
            [
                'title_sk' => 'Farský ples',
                'title_en' => 'Ball',
                'content_sk' => 'Aj tento rok sme dostali pozvanie na ples farnosti Teplická, v rámci programu sa hudobne predstavila aj naša kapela. ',
                'content_en' => 'This year, we were also invited to the Teplická parish ball, where our band performed as part of the program.',
                'inCalendar' => false,
                'inHome' => false,
                'inGallery' => true,
                'archived' => false,
                'main_pic' => 'images/events/ples2026.jpg',
                'exact' => true,
                'dates' => ['2026-02-07'],
                'files' => ['https://photos.app.goo.gl/MtegKRwmDR8nmfzt7'],
            ],
        ];

        foreach ($events as $data) {
            $event = Event::create([
                'title_sk' => $data['title_sk'],
                'title_en' => $data['title_en'],
                'content_sk' => $data['content_sk'],
                'content_en' => $data['content_en'],
                'inCalendar' => $data['inCalendar'],
                'inHome' => $data['inHome'],
                'inGallery' => $data['inGallery'],
                'archived' => $data['archived'],
                'main_pic' => $data['main_pic'] ?? null,
                'color' => $data['color'] ?? null,
            ]);

            foreach ($data['dates'] as $date) {
                EventDate::create([
                    'event_id' => $event->id,
                    'date' => $date,
                    'exact' => $data['exact'] ?? false,
                ]);
            }
            if (!empty($data['files'])) {
                foreach ($data['files'] as $file) {
                    $event->files()->create([
                        'url' => $file,
                        'type' => 'image',
                    ]);
                }
            }
        }
    }
}
